# Introduction to NumPy

In [Tutorial 1](../Tutorial_01), you have seen list, tuple and dictionaries (and we hinted at sets). However, these are not particularly useful when you want to do numerical calculations, or matrix operations. You could try to write a for loop that would iterate through each element, however Python is very slow with operations like that. 

A better (more Pythonic) way is to use the package known as `numpy`. Numpy arrays are similar to lists and tuples etc. in that they hold multiple values. However, all elements in a numpy array must be of the same data type. 

Disregarding that small setback, however, we now have a lot more functionality in numpy arrays. It is convenient to think of the behaviour of numpy arrays as similar to a row vector.

In [2]:
import numpy as np # This is how you can import packages in python. 

The above line imports the package numpy (which includes all the functions we will be using). The part `as np` renames it to `np` (just for this program, don't worry), which is slightly more convenient. 

Let us assign a numpy array to a variable x. 

In [3]:
x=np.array([1,2,3,4]) # np.array converts any array-like object to a numpy array
#x=[1,2,3,4]
y=2*x
print("{}\n{}".format(x,y))

[1 2 3 4]
[2 4 6 8]


Try the above code with a normal list. Now, hopefully it is clear why `numpy` is powerful. But that is just the beginning!

In [4]:
x = np.arange(0,100, 1) # This is similar to the range function from earlier, except that it returns a numpy array
print(x[[4,5,6,7,8,9,10]])

[ 4  5  6  7  8  9 10]


Trying a similar trick with a list instead: (this should give an error!)

In [5]:
x = [1,2,3,4,5,6,7,8,9,10]
print(x[[0,1,2]])

TypeError: list indices must be integers or slices, not list

So `numpy` also supports indexing with lists, instead of only integers or slices, whereas lists don't. 

Similar to the `len` function, numpy also has several functions to describe an array. These are also available as methods, which can be used as follows:

In [6]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(x.ndim) # number of dimensions. This is a 2D array
print(x.shape) # Shape of array
print(x.size) # Total number of elements in array (product of elements in shape)

2
(3, 3)
9


Multiplication, like addition is element wise. If matrix multiplication is required, we can either convert it into a numpy matrix or use `np.dot()`

In [8]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [9]:
np.matrix(x)*np.matrix(x)

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [10]:
np.dot(x,x)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Comparisons on numpy arrays are easier now

In [11]:
x>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

We can also use conditional expressions like indices

In [12]:
y=np.copy(x) # Simply typing y=x doesnot make a new array, it just adds a reference to the old one.
             # Changes in y will then be reflected in x
y[y>5]=0
y

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0]])

If we just want the indices where a certain condition is satisified, we can use `np.where()`. This is one of the more **important** functions, as we can use it to filter out data according to conditions. 

In [13]:
x=np.array([0,1,2,3,4,5,6,7,0.5,0.6])
indices=np.where(x<5)
x[indices]

array([0. , 1. , 2. , 3. , 4. , 0.5, 0.6])

We can also delete elements using `numpy.delete`. 

Note the array slicing. x is 2 dimensional, and requires 2 indices. `x[:, 0]` returns `np.array[1,4,7]`. Play around with different combinations to become comfortable with using indices, as well as `np.where`. 

Also note the argument of the function called `axis`. For a 2D array, `axis=0` is along the rows, and `axis=1` is along the columns. `np.where` assigns the index to be `(np.array([2]))`. Removing index 2 along the columns results in y. If you wanted to remove the row instead, then use `axis=0`. 

In [14]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
index=np.where(x[:,0]>5)
y=np.delete(x,index,axis=1)
print(y)

[[1 2]
 [4 5]
 [7 8]]


**Make sure you understand the part about indexing, slicing, and using `np.where` and `np.delete`, and are comfortable using it. Try out different arrays that you define yourself, of different dimensions and shapes, and experiment!!**

Other useful functions in numpy like `numpy.arange`, `numpy.linspace` often come in handy. We have already seen `arange`

In [15]:
np.arange(0,1,0.1) # start(inclusive):stop(exclusive):step

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [16]:
np.linspace(0,1,5) #start:stop(inclusive):number of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

That is not even it. Several mathematical functions are also available:

In [17]:
x = np.arange(-np.pi, np.pi, 0.1)
y = np.sin(x)
x_abs = np.abs(x)

In [18]:
y2 = np.exp(x)

If you thought `numpy` has revealed all its cards, it hasn't yet! <br>
You can also find the mean, standard deviation, maximum, minimum of an array, sort an array, do matrix computations and so much more. 

If you feel right now that NumPy is vast, remember we have barely scratched the surface. In this module and the next is where your Googling skills will be put to the test. 

If you want to find the official docstrings for any function, an easy way to get it from Jupyter is to use `?`. For example

In [23]:
# Note that this is a very useful function, since we can use it to filter out data. 
np.loadtxt?

As a final note, we will end the tutorial part of this notebook by introducing `np.loadtxt`, a function that can be used to load a txt file into a numpy array. (If you remember how difficult it was to import a text file using `open` and `.split()`, then you will appreciate this one!)

In [55]:
beehive_data = np.loadtxt('Beehive_data.csv', delimiter=',')
beehive_data

array([[ 6.300e+00,  1.770e+00,  1.000e+02],
       [ 6.390e+00,  1.850e+00,  1.000e+02],
       [ 6.440e+00,  1.850e+00,  1.000e+02],
       [ 6.590e+00,  1.760e+00,  1.000e+02],
       [ 6.610e+00,  1.720e+00,  3.500e+01],
       [ 6.610e+00,  1.720e+00,  4.700e+01],
       [ 6.610e+00,  1.720e+00,  1.700e+01],
       [ 6.670e+00,  1.620e+00,  1.000e+02],
       [ 6.780e+00,  1.570e+00,  1.000e+02],
       [ 6.780e+00,  1.580e+00,  1.000e+02],
       [ 6.850e+00,  1.550e+00,  1.000e+02],
       [ 6.900e+00,  1.640e+00,  1.000e+02],
       [ 7.320e+00,  1.360e+00,  1.000e+02],
       [ 7.450e+00,  1.310e+00,  1.000e+02],
       [ 7.540e+00,  1.270e+00,  1.000e+02],
       [ 7.540e+00,  1.280e+00,  4.300e+01],
       [ 7.540e+00,  1.280e+00,  2.700e+01],
       [ 7.540e+00,  1.280e+00,  3.000e+01],
       [ 7.670e+00,  1.220e+00,  4.300e+01],
       [ 7.670e+00,  1.220e+00,  2.400e+01],
       [ 7.670e+00,  1.220e+00,  3.300e+01],
       [ 7.700e+00,  1.210e+00,  4.300e+01],
       [ 7

Yes, that's it. 

### Your assignment ...
... should you choose to accept it, will be the following:
1. Re-do Tutorial 1 assignment with numpy. (This should be fairly easy, but use only numpy functions to reproduce your results)
2. Use the data from `Beehive_data.csv` to find the distance to the Beehive Cluster. Read on ahead to find out more about the concepts in astronomy you will need to solve this

Data downloaded from [VizieR](https://cdsarc.unistra.fr/viz-bin/cat/V/19), from data used in [Piskunov 1980](https://ui.adsabs.harvard.edu/?#abs/1980BICDS..19...67P)

In [42]:
moon_data = np.loadtxt('Moons_and_planets.csv',delimiter=',',dtype=str)

In [46]:
Mercury=0
Venus=0
Earth=0
Mars=0
Jupiter=0
Saturn=0
Uranus=0
Neptune=0
Pluto=0

for data in moon_data:

    if data[1]=='Mercury':
        Mercury=Mercury+1
    elif data[1]=='Venus':
        Venus=Venus+1
    elif data[1]=='Earth':
        Earth=Earth+1
    elif data[1]=='Mars':
        Mars=Mars+1 
    elif data[1]=='Jupiter':
        Jupiter=Jupiter+1
    elif data[1]=='Saturn':
        Saturn=Saturn+1
    elif data[1]=='Uranus':
        Uranus=Uranus+1
    elif data[1]=='Neptune':
        Neptune=Neptune+1
    elif data[1]=='Pluto':
        Pluto=Pluto+1
print(Mercury ,'\n')
print(Venus, '\n')
print(Earth ,'\n')
print(Mars, '\n')
print(Jupiter, '\n')
print(Saturn ,'\n')
print(Uranus ,'\n')
print(Neptune, '\n')
print(Pluto ,'\n')

0 

0 

1 

2 

79 

82 

27 

14 

5 



In [54]:
sorted_array = sorted(moon_data, key=lambda x: float((x[2])))
for lists in sorted_array:
    print(lists[0],'    ',lists[1],'    ',lists[2],'    ','\n')

S/2009 S 1      Saturn      0.15      

Aegaeon      Saturn      0.33      

S/2010 J 2      Jupiter      0.5      

S/2011 J 2      Jupiter      0.5      

Valetudo      Jupiter      0.5      

S/2017 J 8      Jupiter      0.5      

S/2011 J 1      Jupiter      0.5      

S/2003 J 9      Jupiter      0.5      

S/2003 J 12      Jupiter      0.5      

Euporie      Jupiter      1.0      

Orthosie      Jupiter      1.0      

Sponde      Jupiter      1.0      

Kale      Jupiter      1.0      

Pasithee      Jupiter      1.0      

Mneme      Jupiter      1.0      

Thelxinoe      Jupiter      1.0      

Kallichore      Jupiter      1.0      

Cyllene      Jupiter      1.0      

Kore      Jupiter      1.0      

Herse      Jupiter      1.0      

S/2010 J 1      Jupiter      1.0      

S/2003 J 18      Jupiter      1.0      

Philophrosyne      Jupiter      1.0      

Eupheme      Jupiter      1.0      

S/2003 J 19      Jupiter      1.0      

S/2017 J 2      Jupiter      1.0      


# Magnitudes in Astronomy

Magnitudes are a way to describe how bright an object (in our case, a star) is. It is similar to the decibel system for sound in that magnitudes are logarithmic. They can be calculated according to the formula
$$\rm m = -2.5 \log\left(\frac{F}{F_0}\right)$$
where F is the flux from the star (measured in W m$^{-2}$), and F$_0$ is a reference flux.

To read up more about magnitudes, hit up the [Wikipedia article on it](https://en.wikipedia.org/wiki/Magnitude_(astronomy)#History)

Now, we can calculate the flux of a star at some distance d away as 
$$ F = \frac{L}{4\pi d^2} $$
where L is the Luminosity of the star (measured in W). 

There are a lot of details we have skimmed over (for example, the use of filters) which we will visit again in more detail in `Tutorial 8: Image Reduction`.

As a final note on the data you have been given in `Beehive_data.csv`, the columns are respectively the apparent magnitude of the stars as seen from Earth, the logarithm of the Luminosity(in units of Luminosity of the Sun) of the stars (i.e. $\log(L/L_\odot)$, where $L_\odot$ is the luminosity of the sun), and the probability that the star belongs to the Beehive Cluster.

You must find the distance to the cluster (you are given that the absolute magnitude of the Sun is +4.83). You can do this in two ways:
1. Exclude all the stars with low probability of belonging to the cluster, and then calculate distance for each star, and find the mean.
2. Find the distance for all stars (including the low probability ones) and find the weighted average of the distances, where the weights are the probability.

# Method 1

In [60]:
index=np.where(beehive_data[:,2]<90)
index

(array([  4,   5,   6,  15,  16,  17,  18,  19,  20,  21,  22,  23,  37,
         38,  39,  53,  54,  55,  63,  64,  65,  79,  80,  84,  86,  92,
         99, 102], dtype=int64),)

In [61]:
new_array=np.delete(beehive_data,index,axis=0)
print(new_array)

[[ 6.300e+00  1.770e+00  1.000e+02]
 [ 6.390e+00  1.850e+00  1.000e+02]
 [ 6.440e+00  1.850e+00  1.000e+02]
 [ 6.590e+00  1.760e+00  1.000e+02]
 [ 6.670e+00  1.620e+00  1.000e+02]
 [ 6.780e+00  1.570e+00  1.000e+02]
 [ 6.780e+00  1.580e+00  1.000e+02]
 [ 6.850e+00  1.550e+00  1.000e+02]
 [ 6.900e+00  1.640e+00  1.000e+02]
 [ 7.320e+00  1.360e+00  1.000e+02]
 [ 7.450e+00  1.310e+00  1.000e+02]
 [ 7.540e+00  1.270e+00  1.000e+02]
 [ 7.730e+00  1.200e+00  1.000e+02]
 [ 7.960e+00  1.110e+00  1.000e+02]
 [ 8.020e+00  1.080e+00  1.000e+02]
 [ 8.180e+00  1.010e+00  1.000e+02]
 [ 8.310e+00  9.600e-01  1.000e+02]
 [ 8.330e+00  9.600e-01  1.000e+02]
 [ 8.500e+00  8.900e-01  1.000e+02]
 [ 8.710e+00  8.000e-01  1.000e+02]
 [ 8.810e+00  7.600e-01  1.000e+02]
 [ 8.890e+00  7.300e-01  1.000e+02]
 [ 9.000e+00  6.900e-01  1.000e+02]
 [ 9.040e+00  6.700e-01  1.000e+02]
 [ 9.230e+00  6.000e-01  1.000e+02]
 [ 9.370e+00  5.500e-01  1.000e+02]
 [ 9.390e+00  5.400e-01  1.000e+02]
 [ 9.420e+00  5.300e-01  1.0

In [62]:
logd=(new_array[:,0]+2.5*new_array[:,1]+0.17)/5
distance=10**logd
distance

array([151.00801542, 172.5837892 , 176.60378207, 170.6082389 ,
       150.66070662, 149.62356561, 151.35612484, 151.00801542,
       171.39573075, 150.66070662, 151.00801542, 150.31419661,
       151.35612484, 151.70503675, 150.66070662, 149.62356561,
       149.96848355, 151.35612484, 151.00801542, 149.96848355,
       149.96848355, 150.31419661, 151.00801542, 150.31419661,
       151.35612484, 152.40527538, 152.05475297, 152.40527538,
       152.75660582, 152.05475297, 152.40527538, 151.35612484,
       152.40527538, 153.81546403, 153.10874617, 152.75660582,
       153.10874617, 153.81546403, 153.10874617, 153.46169828,
       153.46169828, 153.10874617, 155.59656316, 154.52544395,
       154.52544395, 155.238701  , 155.95525028, 155.238701  ,
       155.59656316, 158.12480393, 155.95525028, 157.76112697,
       156.67510701, 162.55487558, 159.58791472, 156.67510701,
       156.31476426, 159.22087271, 170.6082389 , 162.18100974,
       162.55487558, 179.0605854 , 166.34126504, 166.72

In [64]:
summ=0
for i in distance:
    summ=summ+i
average=summ/len(distance)
average

159.9814397624894

# Method 2

In [68]:
logd=(beehive_data[:,0]+2.5*beehive_data[:,1]+0.17)/5
distance_new=10**logd
distance_new

array([151.00801542, 172.5837892 , 176.60378207, 170.6082389 ,
       164.43717232, 164.43717232, 164.43717232, 150.66070662,
       149.62356561, 151.35612484, 151.00801542, 171.39573075,
       150.66070662, 151.00801542, 150.31419661, 152.05475297,
       152.05475297, 152.05475297, 150.66070662, 150.66070662,
       150.66070662, 151.00801542, 151.00801542, 151.00801542,
       151.35612484, 151.70503675, 150.66070662, 149.62356561,
       149.96848355, 151.35612484, 151.00801542, 149.96848355,
       149.96848355, 150.31419661, 151.00801542, 150.31419661,
       151.35612484, 153.46169828, 153.46169828, 153.46169828,
       152.40527538, 152.05475297, 152.40527538, 152.75660582,
       152.05475297, 152.40527538, 151.35612484, 152.40527538,
       153.81546403, 153.10874617, 152.75660582, 153.10874617,
       153.81546403, 155.238701  , 155.238701  , 155.238701  ,
       153.10874617, 153.46169828, 153.46169828, 153.10874617,
       155.59656316, 154.52544395, 154.52544395, 157.03

In [70]:
summ_dist=0
summ_weights=0
for i in range(len(distance_new)):
    summ_dist=summ_dist+distance_new[i]*beehive_data[:,2][i]
    summ_weights=summ_weights+beehive_data[:,2][i]
average=summ_dist/summ_weights
average

159.5464083490186

Good Luck!